single(fortytwo-coldplay,508).
single(angels-dont-kill-dvd-children-of-bodom,686).
single(animals-coldplay,572).
single(are-you-dead-yet-promotional-video-children-of-bodom,712).
single(bed-of-razorz-children-of-bodom,627).
single(chant-des-druides-manau,1316).
single(confession-manau,1338).
single(dafunkamanau-manau,1237).
single(dead-mans-hand-on-you-children-of-bodom,585).
single(deadnight-warrior-children-of-bodom,673).
single(deadnight-warrior-promotional-video-children-of-bodom,679).
single(dernier-combat-manau,887).
single(des-kilos-manau,1343).
single(done-with-everything-die-for-nothing-dvd-children-of-bodom,616).
single(dont-panic-coldplay,463).
single(faut-pas-faire-chier-mm-manau,1360).
single(fest-noz-de-paname-manau,1581).
single(god-put-a-smile-upon-your-face-dvd-coldplay,593).
single(gravity-coldplay,552).
single(green-eyes-coldplay,573).
single(hate-me-children-of-bodom,712).
single(hellhounds-on-my-trail-dvd-children-of-bodom,929).
single(hellion-children-of-bodom,602).
single(high-speed-coldplay,438).
single(hopeful-transmission-coldplay,318).
single(in-my-place-live-coldplay,558).
single(je-parle-manau,1103).
single(lovers-in-japan-osaka-sun-mix-coldplay,674).
single(mais-qui-est-la-belette-manau,989).
single(now-my-feet-wont-touch-the-ground-coldplay,484).
single(one-bottle-and-a-knee-deep-children-of-bodom,754).
single(panique-celtique-manau,961).
single(postcards-from-far-away-coldplay,319).
single(poupe-manau,1338).
single(pour-me-live-at-the-hollywood-bowl-coldplay,515).
single(princess-of-china-coldplay,645).
single(red-light-in-my-eyes-pt-2-children-of-bodom,716).
single(roundtrip-to-hell-and-back-children-of-bodom,589).
single(shovel-knockout-video-children-of-bodom,612).
single(speed-of-sound-multimedia-track-coldplay,857).
single(talk-dirty-to-me-children-of-bodom,648).
single(til-kingdom-come-coldplay,651).
single(touch-like-angel-of-death-children-of-bodom,725).
single(touch-like-angel-of-deathhummel-gets-the-rockets-children-of-bodom,731).
single(tribu-de-dana-manau,1411).
single(up-with-the-birds-coldplay,624).
single(violet-hill-coldplay,696).
single(viva-la-vida-full-album-version-coldplay,823).
single(waiting-cover-children-of-bodom,798).
single(war-inside-my-head-cover-children-of-bodom,600).
single(were-not-gonna-fall-children-of-bodom,647).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social-coldplay,602).
