single(fortytwo-coldplay,381).
single(angels-dont-kill-dvd-children-of-bodom,594).
single(animals-coldplay,473).
single(are-you-dead-yet-promotional-video-children-of-bodom,613).
single(bed-of-razorz-children-of-bodom,549).
single(chant-des-druides-manau,1380).
single(confession-manau,1400).
single(dafunkamanau-manau,1265).
single(dead-mans-hand-on-you-children-of-bodom,509).
single(deadnight-warrior-children-of-bodom,593).
single(deadnight-warrior-promotional-video-children-of-bodom,595).
single(dernier-combat-manau,866).
single(des-kilos-manau,1356).
single(done-with-everything-die-for-nothing-dvd-children-of-bodom,552).
single(dont-panic-coldplay,355).
single(faut-pas-faire-chier-mm-manau,1411).
single(fest-noz-de-paname-manau,1684).
single(god-put-a-smile-upon-your-face-dvd-coldplay,484).
single(gravity-coldplay,438).
single(green-eyes-coldplay,473).
single(hate-me-children-of-bodom,662).
single(hellhounds-on-my-trail-dvd-children-of-bodom,870).
single(hellion-children-of-bodom,521).
single(high-speed-coldplay,310).
single(hopeful-transmission-coldplay,205).
single(in-my-place-live-coldplay,455).
single(je-parle-manau,1127).
single(lovers-in-japan-osaka-sun-mix-coldplay,597).
single(mais-qui-est-la-belette-manau,966).
single(now-my-feet-wont-touch-the-ground-coldplay,368).
single(one-bottle-and-a-knee-deep-children-of-bodom,687).
single(panique-celtique-manau,955).
single(postcards-from-far-away-coldplay,206).
single(poupe-manau,1401).
single(pour-me-live-at-the-hollywood-bowl-coldplay,395).
single(princess-of-china-coldplay,537).
single(red-light-in-my-eyes-pt-2-children-of-bodom,668).
single(roundtrip-to-hell-and-back-children-of-bodom,502).
single(shovel-knockout-video-children-of-bodom,533).
single(speed-of-sound-multimedia-track-coldplay,778).
single(talk-dirty-to-me-children-of-bodom,567).
single(til-kingdom-come-coldplay,553).
single(touch-like-angel-of-death-children-of-bodom,656).
single(touch-like-angel-of-deathhummel-gets-the-rockets-children-of-bodom,667).
single(tribu-de-dana-manau,1483).
single(up-with-the-birds-coldplay,555).
single(violet-hill-coldplay,630).
single(viva-la-vida-full-album-version-coldplay,778).
single(waiting-cover-children-of-bodom,733).
single(war-inside-my-head-cover-children-of-bodom,516).
single(were-not-gonna-fall-children-of-bodom,565).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social-coldplay,507).
