single(fortytwo-coldplay,521).
single(angels-dont-kill-dvd-children-of-bodom,728).
single(animals-coldplay,587).
single(are-you-dead-yet-promotional-video-children-of-bodom,759).
single(bed-of-razorz-children-of-bodom,664).
single(chant-des-druides-manau,1487).
single(confession-manau,1521).
single(dafunkamanau-manau,1373).
single(dead-mans-hand-on-you-children-of-bodom,617).
single(deadnight-warrior-children-of-bodom,729).
single(deadnight-warrior-promotional-video-children-of-bodom,731).
single(dernier-combat-manau,997).
single(des-kilos-manau,1485).
single(done-with-everything-die-for-nothing-dvd-children-of-bodom,657).
single(dont-panic-coldplay,463).
single(faut-pas-faire-chier-mm-manau,1534).
single(fest-noz-de-paname-manau,1779).
single(god-put-a-smile-upon-your-face-dvd-coldplay,604).
single(gravity-coldplay,561).
single(green-eyes-coldplay,588).
single(hate-me-children-of-bodom,777).
single(hellhounds-on-my-trail-dvd-children-of-bodom,1013).
single(hellion-children-of-bodom,637).
single(high-speed-coldplay,426).
single(hopeful-transmission-coldplay,292).
single(in-my-place-live-coldplay,569).
single(je-parle-manau,1250).
single(lovers-in-japan-osaka-sun-mix-coldplay,715).
single(mais-qui-est-la-belette-manau,1104).
single(now-my-feet-wont-touch-the-ground-coldplay,491).
single(one-bottle-and-a-knee-deep-children-of-bodom,816).
single(panique-celtique-manau,1071).
single(postcards-from-far-away-coldplay,299).
single(poupe-manau,1517).
single(pour-me-live-at-the-hollywood-bowl-coldplay,520).
single(princess-of-china-coldplay,671).
single(red-light-in-my-eyes-pt-2-children-of-bodom,783).
single(roundtrip-to-hell-and-back-children-of-bodom,612).
single(shovel-knockout-video-children-of-bodom,649).
single(speed-of-sound-multimedia-track-coldplay,913).
single(talk-dirty-to-me-children-of-bodom,684).
single(til-kingdom-come-coldplay,691).
single(touch-like-angel-of-death-children-of-bodom,784).
single(touch-like-angel-of-deathhummel-gets-the-rockets-children-of-bodom,792).
single(tribu-de-dana-manau,1606).
single(up-with-the-birds-coldplay,675).
single(violet-hill-coldplay,743).
single(viva-la-vida-full-album-version-coldplay,904).
single(waiting-cover-children-of-bodom,860).
single(war-inside-my-head-cover-children-of-bodom,633).
single(were-not-gonna-fall-children-of-bodom,693).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social-coldplay,627).
