single(fortytwo-coldplay,500).
single(angels-dont-kill-dvd-children-of-bodom,732).
single(animals-coldplay,578).
single(are-you-dead-yet-promotional-video-children-of-bodom,746).
single(bed-of-razorz-children-of-bodom,658).
single(chant-des-druides-manau,1513).
single(confession-manau,1532).
single(dafunkamanau-manau,1384).
single(dead-mans-hand-on-you-children-of-bodom,616).
single(deadnight-warrior-children-of-bodom,721).
single(deadnight-warrior-promotional-video-children-of-bodom,720).
single(dernier-combat-manau,996).
single(des-kilos-manau,1503).
single(done-with-everything-die-for-nothing-dvd-children-of-bodom,661).
single(dont-panic-coldplay,460).
single(faut-pas-faire-chier-mm-manau,1544).
single(fest-noz-de-paname-manau,1803).
single(god-put-a-smile-upon-your-face-dvd-coldplay,594).
single(gravity-coldplay,548).
single(green-eyes-coldplay,582).
single(hate-me-children-of-bodom,778).
single(hellhounds-on-my-trail-dvd-children-of-bodom,1007).
single(hellion-children-of-bodom,633).
single(high-speed-coldplay,409).
single(hopeful-transmission-coldplay,283).
single(in-my-place-live-coldplay,564).
single(je-parle-manau,1254).
single(lovers-in-japan-osaka-sun-mix-coldplay,711).
single(mais-qui-est-la-belette-manau,1105).
single(now-my-feet-wont-touch-the-ground-coldplay,481).
single(one-bottle-and-a-knee-deep-children-of-bodom,813).
single(panique-celtique-manau,1071).
single(postcards-from-far-away-coldplay,288).
single(poupe-manau,1529).
single(pour-me-live-at-the-hollywood-bowl-coldplay,510).
single(princess-of-china-coldplay,668).
single(red-light-in-my-eyes-pt-2-children-of-bodom,786).
single(roundtrip-to-hell-and-back-children-of-bodom,617).
single(shovel-knockout-video-children-of-bodom,643).
single(speed-of-sound-multimedia-track-coldplay,922).
single(talk-dirty-to-me-children-of-bodom,686).
single(til-kingdom-come-coldplay,685).
single(touch-like-angel-of-death-children-of-bodom,786).
single(touch-like-angel-of-deathhummel-gets-the-rockets-children-of-bodom,800).
single(tribu-de-dana-manau,1622).
single(up-with-the-birds-coldplay,672).
single(violet-hill-coldplay,741).
single(viva-la-vida-full-album-version-coldplay,904).
single(waiting-cover-children-of-bodom,858).
single(war-inside-my-head-cover-children-of-bodom,631).
single(were-not-gonna-fall-children-of-bodom,692).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social-coldplay,635).
