single(136,512).
single(42,387).
single(amsterdam-dvd,577).
single(amsterdam,573).
single(animals,480).
single(bigger-stronger,391).
single(brothers-and-sisters,464).
single(careful-where-you-stand,444).
single(cemeteries-of-london,554).
single(charlie-brown,521).
single(christmas-lights,658).
single(clocks-edit,557).
single(clocks-live,552).
single(clocks,547).
single(crests-of-waves,580).
single(daylight-dvd,457).
single(daylight,442).
single(death-and-all-his-friends,419).
single(dont-let-it-break-your-heart,496).
single(dont-panic,361).
single(easy-to-please,296).
single(escapist,235).
single(every-teardrop-is-a-waterfall,706).
single(everythings-not-lost,480).
single(fix-you-dvd,510).
single(fix-you-edit,511).
single(fix-you,507).
single(fix-you-multimedia-track,519).
single(for-you,374).
single(glass-of-water,611).
single(god-put-a-smile-upon-your-face-dvd,489).
single(god-put-a-smile-upon-your-face,486).
single(gravity-audiomultimedia-track,458).
single(gravity,446).
single(green-eyes,481).
single(hardest-part,517).
single(help-is-round-the-corner,451).
single(high-speed,316).
single(hopeful-transmission,211).
single(how-you-see-the-world-live-from-earls-court,615).
single(hurts-like-heaven,702).
single(i-ran-away,548).
single(in-my-place-dvd,455).
single(in-my-place-live,460).
single(in-my-place,451).
single(in-my-place-multimedia-track,463).
single(life-in-technicolor-ii,520).
single(life-in-technicolor,211).
single(life-in-technicolor-pt-2,531).
single(life-is-for-living-dvd,401).
single(lips-like-sugar,505).
single(lost,465).
single(lost-with-jay-z,837).
single(lovers-in-japan-osaka-sun-mix,602).
single(lovers-in-japanreign-of-love,588).
single(low,586).
single(major-minus,513).
single(message,507).
single(mmix,196).
single(moses,537).
single(murder,364).
single(mylo-xyloto,204).
single(no-more-keeping-my-feet-on-the-ground,541).
single(no-more-keeping-my-feet-on-the-ground-taken-from-the-safety-ep,556).
single(now-my-feet-wont-touch-the-ground,372).
single(one-i-love-dvd,267).
single(one-i-love,262).
single(only-superstition,546).
single(parachutes,272).
single(paradise,545).
single(politik-dvd,471).
single(politik,467).
single(postcards-from-far-away,214).
single(pour-me-live-at-the-hollywood-bowl,399).
single(princess-of-china,544).
single(proof-audiomultimedia-track,386).
single(proof,370).
single(prospekts-marchpoppyfields,546).
single(rainy-day,588).
single(rush-of-blood-to-the-head,750).
single(scientist-dvd,587).
single(scientist,575).
single(see-you-soon,404).
single(shiver,583).
single(sleeping-sun-audiomultimedia-track,501).
single(sparks,400).
single(speed-of-sound-dvd,775).
single(speed-of-sound,772).
single(speed-of-sound-multimedia-track,782).
single(spies,573).
single(square-one,634).
single(strawberry-swing,514).
single(such-a-rush,419).
single(swallowed-in-the-sea,660).
single(talk-album-version,647).
single(talk,636).
single(talk-multimedia-track,648).
single(the-scientist,589).
single(things-i-dont-understand-audiomultimedia-track,531).
single(things-i-dont-understand,518).
single(til-kingdom-come-hidden-track,566).
single(til-kingdom-come,559).
single(trouble-dvd,450).
single(trouble,446).
single(twisted-logic,507).
single(ufo,405).
single(up-in-flames,352).
single(up-with-the-birds,561).
single(us-against-the-world,638).
single(user,123).
single(violet-hill,636).
single(viva-la-vida-full-album-version,785).
single(viva-la-vida,768).
single(viva-la-vida-radio-edit,791).
single(warning-sign,466).
single(we-never-change,416).
single(what-if,484).
single(whisper,425).
single(white-shadow,663).
single(white-shadows,656).
single(world-turned-upside-down-audiomultimedia-track,707).
single(world-turned-upside-down,693).
single(xy,444).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social,513).
single(yellow-live,482).
single(yellow,480).
single(yes,560).
single(you-only-live-twice-live-from-norway,397).
single(you-only-live-twice,392).
